services:
  postgres:
    image: postgres:16-alpine
    container_name: pikuu-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pikuu-db
    volumes:
      - pikuu-db:/var/lib/postgresql/data

volumes:
  pikuu-db:
    driver: local
